package;

import flixel.input.FlxBaseKeyList;
import flixel.FlxG;
import gametime.Clock;
import world.MapGenerator;

class Shared {
	public static inline var TILE_WIDTH:Int = 32;
	public static inline var TILE_HEIGHT:Int = 32;
	public static var mapGenerator:MapGenerator;
	public static var player:Player;
	public static var clock:Clock; 
	public static var supportedKeys:Map<String, Int> = [
		"ANY"		=> -2,
		"NONE"		=> -1,
		"A"			=> 65,
		"B"			=> 66,
		"C"			=> 67,
		"D"			=> 68,
		"E"			=> 69,
		"F"			=> 70,
		"G"			=> 71,
		"H"			=> 72,
		"I"			=> 73,
		"J"			=> 74,
		"K"			=> 75,
		"L"			=> 76,
		"M"			=> 77,
		"N"			=> 78,
		"O"			=> 79,
		"P"			=> 80,
		"Q"			=> 81,
		"R"			=> 82,
		"S"			=> 83,
		"T"			=> 84,
		"U"			=> 85,
		"V"			=> 86,
		"W"			=> 87,
		"X"			=> 88,
		"Y"			=> 89,
		"Z"			=> 90,
		"ZERO"		=> 48,
		"ONE"		=> 49,
		"TWO"		=> 50,
		"THREE"		=> 51,
		"FOUR"		=> 52,
		"FIVE"		=> 53,
		"SIX"		=> 54,
		"SEVEN"		=> 55,
		"EIGHT"		=> 56,
		"NINE"		=> 57,
		"PAGEUP"  	=> 33,
		"PAGEDOWN"	=> 34,
		"HOME"		=> 36,
		"END"		=> 35,
		"INSERT"	=> 45,
		"ESCAPE"	=> 27,
		"MINUS"		=> 189,
		"PLUS"		=> 187,
		"DELETE"	=> 46,
		"BACKSPACE"	=> 8,
		"LBRACKET" 	=> 219,
		"RBRACKET" 	=> 221,
		"BACKSLASH" => 220,
		"CAPSLOCK"  => 20,
		"SEMICOLON" => 186,
		"QUOTE"		=> 222,
		"ENTER"		=> 13,
		"SHIFT"		=> 16,
		"COMMA"		=> 188,
		"PERIOD"	=> 190,
		"SLASH"		=> 191,
		"GRAVEACCENT"	=> 192,
		"CONTROL"		=> 17,
		"ALT"			=> 18,
		"SPACE"			=> 32,
		"UP"			=> 38,
		"DOWN"			=> 40,
		"LEFT"			=> 37,
		"RIGHT"			=> 39,
		"TAB"			=> 9,
		"PRINTSCREEN" 	=> 301,
		"F1" 	=> 112,
		"F2" 	=> 113,
		"F3" 	=> 114,
		"F4" 	=> 115,
		"F5" 	=> 116,
		"F6" 	=> 117,
		"F7" 	=> 118,
		"F8" 	=> 119,
		"F9" 	=> 120,
		"F10" 	=> 121,
		"F11" 	=> 122,
		"F12" 	=> 123,
		"NUMPADZERO"	=> 96,
		"NUMPADONE"		=> 97,
		"NUMPADTWO"		=> 98,
		"NUMPADTHREE"	=> 99,
		"NUMPADFOUR"	=> 100,
		"NUMPADFIVE"	=> 101,
		"NUMPADSIX"		=> 102,
		"NUMPADSEVEN"	=> 103,
		"NUMPADEIGHT"	=> 104,
		"NUMPADNINE"	=> 105,
		"NUMPADMINUS"	=> 109,
		"NUMPADPLUS"	=> 107,
		"NUMPADPERIOD"	=> 110,
		"NUMPADMULTIPLY" => 106 
	];
	public static var supportedButtons:Map<String, Int> = [
		"ANY"		=> -2,
		"NONE" 		=> -1,
		"A"			=> 0,
		"B"			=> 1,
		"X"			=> 2,
		"Y"			=> 3,
		"LEFT_SHOULDER"		=> 4,
		"RIGHT_SHOULDER"	=> 5,
		"BACK"				=> 6,
		"START"				=> 7,
		"LEFT_STICK_CLICK"	=> 8,
		"RIGHT_STICK_CLICK"	=> 9,
		"GUIDE"				=> 10,
		"DPAD_UP"			=> 11,
		"DPAD_DOWN"			=> 12,
		"DPAD_LEFT"			=> 13,
		"DPAD_RIGHT"		=> 14,
		"LEFT_TRIGGER_BUTTON"	=> 15,
		"RIGHT_TRIGGER_BUTTON"	=> 16,
		"LEFT_TRIGGER"			=> 17,
		"RIGHT_TRIGGER"			=> 18,
		"LEFT_ANALOG_STICK"		=> 19,
		"RIGHT_ANALOG_STICK"	=> 20,
		"DPAD"					=> 21,
		"LEFT_TRIGGER_FAKE"		=> 22,
		"RIGHT_TRIGGER_FAKE"	=> 23,
		"LEFT_STICK_FAKE"		=> 24,
		"RIGHT_STICK_FAKE"		=> 25,
		"TILT_PITCH"	=> 26,
		"TILT_ROLL"		=> 27,
		"POINTER_X"		=> 28,
		"POINTER_Y"		=> 29,
		"EXTRA_0"		=> 30,
		"EXTRA_1"		=> 31,
		"EXTRA_2"		=> 32,
		"EXTRA_3"		=> 33 
	];

	public static function init() {
		mapGenerator = new MapGenerator();
		player = new Player();
		clock = new Clock();
	}
}